### PR TITLE
Fix: Highlight colors don't update on color scheme change

### PR DESCRIPTION
**Pull request by eado**
Added a autocmd handler that calls setup_highlight

### CODE REVIEW

**Comment by rachartier** [comment]
Thanks for the PR !

**Comment by eado** [comment]
All thanks to you; really enjoying this plugin!

**Comment by rachartier** [comment]
I'm sorry but it seems like there is a bug for a majority of users with this PR. I'll try to fix it, but I've reverted the PR for now.

I'll take a look!

**Comment by eado** [comment]
Apologies. I found the bug; I'm pretty sure this fixes it.

**Pull request merged**
